---
title: "Estimation and Testing Assignment: Appendix"
author:
- "Julian Riemersma, s3812936" 
- "Joris Untersalmberger, s"
date: "28 - 05 - 2019"
output:
  pdf_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE)
```

```{r, include = FALSE}
library(countrycode)
library(xtable)
library(tidyverse)
load("drinks.rda")
```

```{r, echo = FALSE, eval = FALSE}
install.packages("countrycode")
install.packages("xtable")
```


## Exercise 1

```{r}

```

## Exercise 2

**a)**
```{r}
sum_stat <- drinks %>%
  group_by(continent) %>%
  summarize_at(vars(beer_servings:total_litres_of_pure_alcohol), list(Mean = mean, Variance = var))

sum_stat_obs <- drinks %>%
  group_by(continent) %>%
  summarize(Observations = n())

sum_stat <- cbind(sum_stat, sum_stat_obs[, 2])

sum_stat_rounded <- sum_stat
sum_stat_rounded[, 2:9] <- round(sum_stat[, 2:9], 2)

xtable(t(sum_stat_rounded))

sum_stat
```

**b)**
```{r}
alpha <- 1 - 0.985

attach(sum_stat[4, ])

error_eu <- qnorm(1 - alpha / 2) * sqrt(beer_servings_Variance / Observations)

left_eu <- beer_servings_Mean - error_eu
right_eu <- beer_servings_Mean + error_eu

detach(sum_stat[4, ])

attach(sum_stat[5, ])

error_oc <- qt(1 - alpha / 2, df = Observations - 1) * sqrt(beer_servings_Variance / Observations)

left_oc <- beer_servings_Mean - error_oc
right_oc <- beer_servings_Mean + error_oc

detach(sum_stat[5, ])

left_eu
right_eu

left_oc
right_oc
```

**c)**
```{r}
alpha <- 1 - 0.97

eu_spirit_servings_mean <- sum_stat %>%
  slice(4) %>%
  select(spirit_servings_Mean) %>%
  as.numeric

eu_spirit_servings_variance <- sum_stat %>%
  slice(4) %>%
  select(spirit_servings_Variance) %>%
  as.numeric

eu_observations <- sum_stat %>%
  slice(4) %>%
  select(Observations) %>%
  as.numeric

am_spirit_servings_mean <- sum_stat %>%
  slice(2) %>%
  select(spirit_servings_Mean) %>%
  as.numeric

am_spirit_servings_variance <- sum_stat %>%
  slice(2) %>%
  select(spirit_servings_Variance) %>%
  as.numeric

am_observations <- sum_stat %>%
  slice(2) %>%
  select(Observations) %>%
  as.numeric

error_eu_am <- qnorm(1 - alpha / 2) * sqrt(eu_spirit_servings_variance / eu_observations + am_spirit_servings_variance / am_observations)

left_eu_am <- eu_spirit_servings_mean - am_spirit_servings_mean - error_eu_am
right_eu_am <- eu_spirit_servings_mean - am_spirit_servings_mean + error_eu_am

left_eu_am
right_eu_am
```

